spring:
  cloud:
    stream:
      bindings:
        output:
          destination: queue.message
#          binder: local_rabbit
#      binders:
#        local_rabbit:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: localhost
#                port: 5672
#                username: test
#                password: test
#                virtual-host: /