spring:
  cloud:
    stream:
      bindings:
        input: # name of the spring cloud stream channel abstraction
          destination: queue.message # queue where the lowercase message is waiting
        output: # name of the spring cloud stream channel abstraction
          destination: uppercase # queue where the uppercase message goes